# Layer configuration for meta-network-overrides
BBPATH .= ":${LAYERDIR}"

BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-network-overrides"
BBFILE_PATTERN_meta-network-overrides = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-network-overrides = "6"

LAYERDEPENDS_meta-network-overrides = "core"
LAYERSERIES_COMPAT_meta-network-overrides = "scarthgap"
