/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wolfssl_ccbvaultic_ccbVaultIc */

#ifndef _Included_com_wolfssl_ccbvaultic_ccbVaultIc
#define _Included_com_wolfssl_ccbvaultic_ccbVaultIc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wolfssl_ccbvaultic_ccbVaultIc
 * Method:    GetInfoText
 * Signature: (ILjava/nio/ByteBuffer;[J)I
 */
JNIEXPORT jint JNICALL Java_com_wolfssl_ccbvaultic_ccbVaultIc_GetInfoText
  (JNIEnv *, jobject, jint, jobject, jlongArray);

#ifdef __cplusplus
}
#endif
#endif
